/**
 * Generated by Payload — run `npm run generate:types` to regenerate.
 * This file registers custom components for the Payload admin UI.
 */
import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
